[profile.default]
  src = "src"
  out = "out"
  libs = ["lib"]
  fs_permissions = [{access = "read-write", path = "./deployments"}]
  no_match_contract = 'CryticTester|FoundryHandler'
  no_match_test = 'testFork_'

[profile.fork]
  src = "src"
  out = "out"
  libs = ["lib"]
  fs_permissions = [{access = "read-write", path = "./deployments"}]
  no_match_contract = 'CryticTester|FoundryHandler'
  ffi = true
  match_test = 'testFork_'
  no_match_test = 'test_'

[invariant]
  runs = 1000
  fail_on_revert = false

[rpc_endpoints]
  sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
  base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  anvil = "http://127.0.0.1:8545"

[etherscan]
  sepolia = { key = "${API_KEY_ETHERSCAN}" }
  base_sepolia = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
  sort_imports = true
  line_length = 120

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
