[profile.default]
  src = "src"
  out = "out"
  libs = ["lib"]
  fs_permissions = [{access = "read-write", path = "./deployments"}]
  no_match_contract = 'CryticTester|FoundryHandler|FoundryForkTester|FoundryTester'
  no_match_test = 'testFork_'
  solc_version = '0.8.23'
  evm_version = 'shanghai'
  ignored_warnings_from = ["lib/aave-v3-core"]
  optimizer = true
  optimizer_runs = 200

[profile.fork]
  src = "src"
  out = "out"
  libs = ["lib"]
  fs_permissions = [{access = "read-write", path = "./deployments"}]
  no_match_contract = 'CryticTester|FoundryHandler|FoundryTester'
  ffi = true
  no_match_test = 'test_|testFuzz_'

[invariant]
  runs = 1000
  fail_on_revert = false

[rpc_endpoints]
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base = "https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base-production = "https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base_archive = "https://mainnet.base.org"
  anvil = "http://127.0.0.1:8545"

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  base_sepolia = { key = "${API_KEY_ETHERSCAN}" }
  base = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
  sort_imports = true
  line_length = 120

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
