/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type YieldCurveStruct = {
  timeBuckets: BigNumberish[];
  rates: BigNumberish[];
};

export type YieldCurveStructOutput = [BigNumber[], BigNumber[]] & {
  timeBuckets: BigNumber[];
  rates: BigNumber[];
};

export type BorrowAsLimitOrderParamsStruct = {
  maxAmount: BigNumberish;
  curveRelativeTime: YieldCurveStruct;
};

export type BorrowAsLimitOrderParamsStructOutput = [
  BigNumber,
  YieldCurveStructOutput
] & { maxAmount: BigNumber; curveRelativeTime: YieldCurveStructOutput };

export type BorrowAsMarketOrderParamsStruct = {
  lender: string;
  amount: BigNumberish;
  dueDate: BigNumberish;
  exactAmountIn: boolean;
  virtualCollateralFixedLoanIds: BigNumberish[];
};

export type BorrowAsMarketOrderParamsStructOutput = [
  string,
  BigNumber,
  BigNumber,
  boolean,
  BigNumber[]
] & {
  lender: string;
  amount: BigNumber;
  dueDate: BigNumber;
  exactAmountIn: boolean;
  virtualCollateralFixedLoanIds: BigNumber[];
};

export type BorrowerExitParamsStruct = {
  loanId: BigNumberish;
  borrowerToExitTo: string;
};

export type BorrowerExitParamsStructOutput = [BigNumber, string] & {
  loanId: BigNumber;
  borrowerToExitTo: string;
};

export type ClaimParamsStruct = { loanId: BigNumberish };

export type ClaimParamsStructOutput = [BigNumber] & { loanId: BigNumber };

export type CompensateParamsStruct = {
  loanToRepayId: BigNumberish;
  loanToCompensateId: BigNumberish;
  amount: BigNumberish;
};

export type CompensateParamsStructOutput = [BigNumber, BigNumber, BigNumber] & {
  loanToRepayId: BigNumber;
  loanToCompensateId: BigNumber;
  amount: BigNumber;
};

export type InitializeFixedParamsStruct = {
  crOpening: BigNumberish;
  crLiquidation: BigNumberish;
  collateralPremiumToLiquidator: BigNumberish;
  collateralPremiumToProtocol: BigNumberish;
  minimumCredit: BigNumberish;
};

export type InitializeFixedParamsStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  crOpening: BigNumber;
  crLiquidation: BigNumber;
  collateralPremiumToLiquidator: BigNumber;
  collateralPremiumToProtocol: BigNumber;
  minimumCredit: BigNumber;
};

export type DepositParamsStruct = {
  token: string;
  amount: BigNumberish;
  to: string;
};

export type DepositParamsStructOutput = [string, BigNumber, string] & {
  token: string;
  amount: BigNumber;
  to: string;
};

export type FixedLoanStruct = {
  faceValue: BigNumberish;
  faceValueExited: BigNumberish;
  lender: string;
  borrower: string;
  dueDate: BigNumberish;
  repaid: boolean;
  folId: BigNumberish;
};

export type FixedLoanStructOutput = [
  BigNumber,
  BigNumber,
  string,
  string,
  BigNumber,
  boolean,
  BigNumber
] & {
  faceValue: BigNumber;
  faceValueExited: BigNumber;
  lender: string;
  borrower: string;
  dueDate: BigNumber;
  repaid: boolean;
  folId: BigNumber;
};

export type FixedLoanOfferStruct = {
  maxAmount: BigNumberish;
  maxDueDate: BigNumberish;
  curveRelativeTime: YieldCurveStruct;
};

export type FixedLoanOfferStructOutput = [
  BigNumber,
  BigNumber,
  YieldCurveStructOutput
] & {
  maxAmount: BigNumber;
  maxDueDate: BigNumber;
  curveRelativeTime: YieldCurveStructOutput;
};

export type BorrowOfferStruct = {
  maxAmount: BigNumberish;
  curveRelativeTime: YieldCurveStruct;
};

export type BorrowOfferStructOutput = [BigNumber, YieldCurveStructOutput] & {
  maxAmount: BigNumber;
  curveRelativeTime: YieldCurveStructOutput;
};

export type UserStruct = {
  loanOffer: FixedLoanOfferStruct;
  borrowOffer: BorrowOfferStruct;
  proxy: string;
  vpBorrowAssetScaledDeposits: BigNumberish;
};

export type UserStructOutput = [
  FixedLoanOfferStructOutput,
  BorrowOfferStructOutput,
  string,
  BigNumber
] & {
  loanOffer: FixedLoanOfferStructOutput;
  borrowOffer: BorrowOfferStructOutput;
  proxy: string;
  vpBorrowAssetScaledDeposits: BigNumber;
};

export type UserViewStruct = {
  user: UserStruct;
  account: string;
  collateralAmount: BigNumberish;
  borrowAmount: BigNumberish;
  debtAmount: BigNumberish;
  vpBorrowAmount: BigNumberish;
};

export type UserViewStructOutput = [
  UserStructOutput,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  user: UserStructOutput;
  account: string;
  collateralAmount: BigNumber;
  borrowAmount: BigNumber;
  debtAmount: BigNumber;
  vpBorrowAmount: BigNumber;
};

export type InitializeGeneralParamsStruct = {
  owner: string;
  priceFeed: string;
  collateralAsset: string;
  borrowAsset: string;
  feeRecipient: string;
  variablePool: string;
};

export type InitializeGeneralParamsStructOutput = [
  string,
  string,
  string,
  string,
  string,
  string
] & {
  owner: string;
  priceFeed: string;
  collateralAsset: string;
  borrowAsset: string;
  feeRecipient: string;
  variablePool: string;
};

export type LendAsLimitOrderParamsStruct = {
  maxAmount: BigNumberish;
  maxDueDate: BigNumberish;
  curveRelativeTime: YieldCurveStruct;
};

export type LendAsLimitOrderParamsStructOutput = [
  BigNumber,
  BigNumber,
  YieldCurveStructOutput
] & {
  maxAmount: BigNumber;
  maxDueDate: BigNumber;
  curveRelativeTime: YieldCurveStructOutput;
};

export type LendAsMarketOrderParamsStruct = {
  borrower: string;
  dueDate: BigNumberish;
  amount: BigNumberish;
  exactAmountIn: boolean;
};

export type LendAsMarketOrderParamsStructOutput = [
  string,
  BigNumber,
  BigNumber,
  boolean
] & {
  borrower: string;
  dueDate: BigNumber;
  amount: BigNumber;
  exactAmountIn: boolean;
};

export type LiquidateFixedLoanParamsStruct = {
  loanId: BigNumberish;
  minimumCollateralRatio: BigNumberish;
};

export type LiquidateFixedLoanParamsStructOutput = [BigNumber, BigNumber] & {
  loanId: BigNumber;
  minimumCollateralRatio: BigNumber;
};

export type LiquidateFixedLoanWithReplacementParamsStruct = {
  loanId: BigNumberish;
  borrower: string;
  minimumCollateralRatio: BigNumberish;
};

export type LiquidateFixedLoanWithReplacementParamsStructOutput = [
  BigNumber,
  string,
  BigNumber
] & { loanId: BigNumber; borrower: string; minimumCollateralRatio: BigNumber };

export type MoveToVariablePoolParamsStruct = { loanId: BigNumberish };

export type MoveToVariablePoolParamsStructOutput = [BigNumber] & {
  loanId: BigNumber;
};

export type RepayParamsStruct = { loanId: BigNumberish; amount: BigNumberish };

export type RepayParamsStructOutput = [BigNumber, BigNumber] & {
  loanId: BigNumber;
  amount: BigNumber;
};

export type SelfLiquidateFixedLoanParamsStruct = { loanId: BigNumberish };

export type SelfLiquidateFixedLoanParamsStructOutput = [BigNumber] & {
  loanId: BigNumber;
};

export type UpdateConfigParamsStruct = { key: BytesLike; value: BigNumberish };

export type UpdateConfigParamsStructOutput = [string, BigNumber] & {
  key: string;
  value: BigNumber;
};

export type WithdrawParamsStruct = {
  token: string;
  amount: BigNumberish;
  to: string;
};

export type WithdrawParamsStructOutput = [string, BigNumber, string] & {
  token: string;
  amount: BigNumber;
  to: string;
};

export interface SizeInterface extends utils.Interface {
  functions: {
    "UPGRADE_INTERFACE_VERSION()": FunctionFragment;
    "acceptOwnership()": FunctionFragment;
    "activeFixedLoans()": FunctionFragment;
    "borrowAsLimitOrder((uint256,(uint256[],uint256[])))": FunctionFragment;
    "borrowAsMarketOrder((address,uint256,uint256,bool,uint256[]))": FunctionFragment;
    "borrowerExit((uint256,address))": FunctionFragment;
    "claim((uint256))": FunctionFragment;
    "collateralRatio(address)": FunctionFragment;
    "compensate((uint256,uint256,uint256))": FunctionFragment;
    "config()": FunctionFragment;
    "deposit((address,uint256,address))": FunctionFragment;
    "getCredit(uint256)": FunctionFragment;
    "getDebt(uint256)": FunctionFragment;
    "getFOLAssignedCollateral(uint256)": FunctionFragment;
    "getFeeRecipient()": FunctionFragment;
    "getFixedLoan(uint256)": FunctionFragment;
    "getFixedLoanStatus(uint256)": FunctionFragment;
    "getFixedLoans()": FunctionFragment;
    "getUserView(address)": FunctionFragment;
    "getVariablePool()": FunctionFragment;
    "initialize((address,address,address,address,address,address),(uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "isFOL(uint256)": FunctionFragment;
    "isLiquidatable(address)": FunctionFragment;
    "isLiquidatable(uint256)": FunctionFragment;
    "lendAsLimitOrder((uint256,uint256,(uint256[],uint256[])))": FunctionFragment;
    "lendAsMarketOrder((address,uint256,uint256,bool))": FunctionFragment;
    "liquidateFixedLoan((uint256,uint256))": FunctionFragment;
    "liquidateFixedLoanWithReplacement((uint256,address,uint256))": FunctionFragment;
    "moveToVariablePool((uint256))": FunctionFragment;
    "multicall(bytes[])": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingOwner()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "repay((uint256,uint256))": FunctionFragment;
    "selfLiquidateFixedLoan((uint256))": FunctionFragment;
    "tokens()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateConfig((bytes32,uint256))": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "withdraw((address,uint256,address))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptOwnership"
      | "activeFixedLoans"
      | "borrowAsLimitOrder"
      | "borrowAsMarketOrder"
      | "borrowerExit"
      | "claim"
      | "collateralRatio"
      | "compensate"
      | "config"
      | "deposit"
      | "getCredit"
      | "getDebt"
      | "getFOLAssignedCollateral"
      | "getFeeRecipient"
      | "getFixedLoan"
      | "getFixedLoanStatus"
      | "getFixedLoans"
      | "getUserView"
      | "getVariablePool"
      | "initialize"
      | "isFOL"
      | "isLiquidatable(address)"
      | "isLiquidatable(uint256)"
      | "lendAsLimitOrder"
      | "lendAsMarketOrder"
      | "liquidateFixedLoan"
      | "liquidateFixedLoanWithReplacement"
      | "moveToVariablePool"
      | "multicall"
      | "owner"
      | "pendingOwner"
      | "proxiableUUID"
      | "renounceOwnership"
      | "repay"
      | "selfLiquidateFixedLoan"
      | "tokens"
      | "transferOwnership"
      | "updateConfig"
      | "upgradeToAndCall"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeFixedLoans",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrowAsLimitOrder",
    values: [BorrowAsLimitOrderParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowAsMarketOrder",
    values: [BorrowAsMarketOrderParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowerExit",
    values: [BorrowerExitParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [ClaimParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralRatio",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "compensate",
    values: [CompensateParamsStruct]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [DepositParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFOLAssignedCollateral",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFixedLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFixedLoanStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFixedLoans",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getUserView", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getVariablePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [InitializeGeneralParamsStruct, InitializeFixedParamsStruct]
  ): string;
  encodeFunctionData(functionFragment: "isFOL", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "isLiquidatable(address)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isLiquidatable(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lendAsLimitOrder",
    values: [LendAsLimitOrderParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "lendAsMarketOrder",
    values: [LendAsMarketOrderParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateFixedLoan",
    values: [LiquidateFixedLoanParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateFixedLoanWithReplacement",
    values: [LiquidateFixedLoanWithReplacementParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "moveToVariablePool",
    values: [MoveToVariablePoolParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [RepayParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "selfLiquidateFixedLoan",
    values: [SelfLiquidateFixedLoanParamsStruct]
  ): string;
  encodeFunctionData(functionFragment: "tokens", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateConfig",
    values: [UpdateConfigParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [WithdrawParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeFixedLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowAsLimitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowAsMarketOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowerExit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "compensate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCredit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFOLAssignedCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFixedLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFixedLoanStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFixedLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVariablePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isFOL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isLiquidatable(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isLiquidatable(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lendAsLimitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lendAsMarketOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateFixedLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateFixedLoanWithReplacement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moveToVariablePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "selfLiquidateFixedLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "Initialized(uint64)": EventFragment;
    "OwnershipTransferStarted(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface InitializedEventObject {
  version: BigNumber;
}
export type InitializedEvent = TypedEvent<[BigNumber], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferStartedEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferStartedEvent = TypedEvent<
  [string, string],
  OwnershipTransferStartedEventObject
>;

export type OwnershipTransferStartedEventFilter =
  TypedEventFilter<OwnershipTransferStartedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface Size extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SizeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<[string]>;

    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    activeFixedLoans(overrides?: CallOverrides): Promise<[BigNumber]>;

    borrowAsLimitOrder(
      params: BorrowAsLimitOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    borrowAsMarketOrder(
      params: BorrowAsMarketOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    borrowerExit(
      params: BorrowerExitParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    claim(
      params: ClaimParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    collateralRatio(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    compensate(
      params: CompensateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    config(
      overrides?: CallOverrides
    ): Promise<[InitializeFixedParamsStructOutput]>;

    deposit(
      params: DepositParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getCredit(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getDebt(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getFOLAssignedCollateral(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getFeeRecipient(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    getFixedLoan(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[FixedLoanStructOutput]>;

    getFixedLoanStatus(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getFixedLoans(
      overrides?: CallOverrides
    ): Promise<[FixedLoanStructOutput[]]>;

    getUserView(
      user: string,
      overrides?: CallOverrides
    ): Promise<[UserViewStructOutput]>;

    getVariablePool(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    initialize(
      g: InitializeGeneralParamsStruct,
      f: InitializeFixedParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isFOL(loanId: BigNumberish, overrides?: CallOverrides): Promise<[boolean]>;

    "isLiquidatable(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isLiquidatable(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    lendAsLimitOrder(
      params: LendAsLimitOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    lendAsMarketOrder(
      params: LendAsMarketOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    liquidateFixedLoan(
      params: LiquidateFixedLoanParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    liquidateFixedLoanWithReplacement(
      params: LiquidateFixedLoanWithReplacementParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    moveToVariablePool(
      params: MoveToVariablePoolParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingOwner(overrides?: CallOverrides): Promise<[string]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    repay(
      params: RepayParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    selfLiquidateFixedLoan(
      params: SelfLiquidateFixedLoanParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    tokens(overrides?: CallOverrides): Promise<[string, string, string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateConfig(
      params: UpdateConfigParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdraw(
      params: WithdrawParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

  acceptOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  activeFixedLoans(overrides?: CallOverrides): Promise<BigNumber>;

  borrowAsLimitOrder(
    params: BorrowAsLimitOrderParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  borrowAsMarketOrder(
    params: BorrowAsMarketOrderParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  borrowerExit(
    params: BorrowerExitParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  claim(
    params: ClaimParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  collateralRatio(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  compensate(
    params: CompensateParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  config(overrides?: CallOverrides): Promise<InitializeFixedParamsStructOutput>;

  deposit(
    params: DepositParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getCredit(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getDebt(loanId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  getFOLAssignedCollateral(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFeeRecipient(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>;

  getFixedLoan(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<FixedLoanStructOutput>;

  getFixedLoanStatus(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  getFixedLoans(overrides?: CallOverrides): Promise<FixedLoanStructOutput[]>;

  getUserView(
    user: string,
    overrides?: CallOverrides
  ): Promise<UserViewStructOutput>;

  getVariablePool(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>;

  initialize(
    g: InitializeGeneralParamsStruct,
    f: InitializeFixedParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isFOL(loanId: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  "isLiquidatable(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isLiquidatable(uint256)"(
    loanId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lendAsLimitOrder(
    params: LendAsLimitOrderParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  lendAsMarketOrder(
    params: LendAsMarketOrderParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  liquidateFixedLoan(
    params: LiquidateFixedLoanParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  liquidateFixedLoanWithReplacement(
    params: LiquidateFixedLoanWithReplacementParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  moveToVariablePool(
    params: MoveToVariablePoolParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  multicall(
    data: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingOwner(overrides?: CallOverrides): Promise<string>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  repay(
    params: RepayParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  selfLiquidateFixedLoan(
    params: SelfLiquidateFixedLoanParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  tokens(overrides?: CallOverrides): Promise<[string, string, string]>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateConfig(
    params: UpdateConfigParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdraw(
    params: WithdrawParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    activeFixedLoans(overrides?: CallOverrides): Promise<BigNumber>;

    borrowAsLimitOrder(
      params: BorrowAsLimitOrderParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    borrowAsMarketOrder(
      params: BorrowAsMarketOrderParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    borrowerExit(
      params: BorrowerExitParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    claim(params: ClaimParamsStruct, overrides?: CallOverrides): Promise<void>;

    collateralRatio(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    compensate(
      params: CompensateParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    config(
      overrides?: CallOverrides
    ): Promise<InitializeFixedParamsStructOutput>;

    deposit(
      params: DepositParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    getCredit(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDebt(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFOLAssignedCollateral(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeeRecipient(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    getFixedLoan(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<FixedLoanStructOutput>;

    getFixedLoanStatus(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    getFixedLoans(overrides?: CallOverrides): Promise<FixedLoanStructOutput[]>;

    getUserView(
      user: string,
      overrides?: CallOverrides
    ): Promise<UserViewStructOutput>;

    getVariablePool(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    initialize(
      g: InitializeGeneralParamsStruct,
      f: InitializeFixedParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    isFOL(loanId: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    "isLiquidatable(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isLiquidatable(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lendAsLimitOrder(
      params: LendAsLimitOrderParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    lendAsMarketOrder(
      params: LendAsMarketOrderParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidateFixedLoan(
      params: LiquidateFixedLoanParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidateFixedLoanWithReplacement(
      params: LiquidateFixedLoanWithReplacementParamsStruct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        liquidatorProfitCollateralAsset: BigNumber;
        liquidatorProfitBorrowAsset: BigNumber;
      }
    >;

    moveToVariablePool(
      params: MoveToVariablePoolParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    multicall(data: BytesLike[], overrides?: CallOverrides): Promise<string[]>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingOwner(overrides?: CallOverrides): Promise<string>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    repay(params: RepayParamsStruct, overrides?: CallOverrides): Promise<void>;

    selfLiquidateFixedLoan(
      params: SelfLiquidateFixedLoanParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    tokens(overrides?: CallOverrides): Promise<[string, string, string]>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateConfig(
      params: UpdateConfigParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      params: WithdrawParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint64)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferStarted(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferStartedEventFilter;
    OwnershipTransferStarted(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferStartedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "Upgraded(address)"(implementation?: string | null): UpgradedEventFilter;
    Upgraded(implementation?: string | null): UpgradedEventFilter;
  };

  estimateGas: {
    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    activeFixedLoans(overrides?: CallOverrides): Promise<BigNumber>;

    borrowAsLimitOrder(
      params: BorrowAsLimitOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    borrowAsMarketOrder(
      params: BorrowAsMarketOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    borrowerExit(
      params: BorrowerExitParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    claim(
      params: ClaimParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    collateralRatio(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    compensate(
      params: CompensateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      params: DepositParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getCredit(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDebt(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFOLAssignedCollateral(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeeRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    getFixedLoan(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFixedLoanStatus(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFixedLoans(overrides?: CallOverrides): Promise<BigNumber>;

    getUserView(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    getVariablePool(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      g: InitializeGeneralParamsStruct,
      f: InitializeFixedParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    isFOL(loanId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "isLiquidatable(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isLiquidatable(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lendAsLimitOrder(
      params: LendAsLimitOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    lendAsMarketOrder(
      params: LendAsMarketOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    liquidateFixedLoan(
      params: LiquidateFixedLoanParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    liquidateFixedLoanWithReplacement(
      params: LiquidateFixedLoanWithReplacementParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    moveToVariablePool(
      params: MoveToVariablePoolParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingOwner(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    repay(
      params: RepayParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    selfLiquidateFixedLoan(
      params: SelfLiquidateFixedLoanParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    tokens(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateConfig(
      params: UpdateConfigParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    withdraw(
      params: WithdrawParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    UPGRADE_INTERFACE_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    activeFixedLoans(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrowAsLimitOrder(
      params: BorrowAsLimitOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    borrowAsMarketOrder(
      params: BorrowAsMarketOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    borrowerExit(
      params: BorrowerExitParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claim(
      params: ClaimParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    collateralRatio(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    compensate(
      params: CompensateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    config(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      params: DepositParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getCredit(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDebt(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFOLAssignedCollateral(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeeRecipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFixedLoan(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFixedLoanStatus(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFixedLoans(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserView(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVariablePool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      g: InitializeGeneralParamsStruct,
      f: InitializeFixedParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isFOL(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isLiquidatable(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isLiquidatable(uint256)"(
      loanId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lendAsLimitOrder(
      params: LendAsLimitOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    lendAsMarketOrder(
      params: LendAsMarketOrderParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    liquidateFixedLoan(
      params: LiquidateFixedLoanParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    liquidateFixedLoanWithReplacement(
      params: LiquidateFixedLoanWithReplacementParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    moveToVariablePool(
      params: MoveToVariablePoolParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    repay(
      params: RepayParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    selfLiquidateFixedLoan(
      params: SelfLiquidateFixedLoanParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    tokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateConfig(
      params: UpdateConfigParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdraw(
      params: WithdrawParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
