name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  foundry:
    strategy:
      fail-fast: true

    name: Foundry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Contract sizes
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Test
        run: |
          forge test -vvv
        id: test

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SIZE_BOT_SSH_KEY }}

      - name: Report coverage
        run: |
          git config --local user.email "dev@size.cash"
          git config --local user.name "Size"
          ./script/update_readme_coverage.sh
          git add README.md
          git commit -m "Update coverage [skip ci]" || true
          git push

  slither:
    strategy:
      fail-fast: true

    name: Slither
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          fail-on: low

  typechain:
    strategy:
      fail-fast: true

    name: Typechain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SIZE_BOT_SSH_KEY }}

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build
        run: forge build

      - name: Install dependencies
        run: npm install

      - name: Generate types
        run: npm run typechain

      - name: Add typechain
        run: |
          git config --local user.email "dev@size.cash"
          git config --local user.name "Size"
          git add types/
          git commit -m "Update types [skip ci]" || true
          git push

  solhint:
    strategy:
      fail-fast: true

    name: Solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: npm install

      - name: Run solhint
        run: npm run solhint